default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: db

development:
  <<: *default
  database: neighborly_development

test:
  <<: *default
  database: neighborly_test
