default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: neighborly_development
  username: neighborly
  password: neighborly

test:
  <<: *default
  database: neighborly_test
  username: neighborly
  password: neighborly

production:
  <<: *default
  database: neighborly_production
  url: <%= ENV['POSTGRESQL_URL'] %>
